/*
Dynamo Web Services is a web service project for administering LucidDB
Copyright (C) 2011 Dynamo Business Intelligence Corporation

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your option)
any later version approved by Dynamo Business Intelligence Corporation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
*/
package com.dynamobi.ws.api;

import javax.jws.WebService;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.jws.WebMethod;

import javax.annotation.security.RolesAllowed;

import com.dynamobi.ws.domain.XMLStructure;
import com.dynamobi.ws.util.AppException;

/**
 * Service to handle suggestion and creation of indexes on tables.
 * @author Kevin Secretan
 */
@WebService(serviceName="AutoIndexService", name="AutoIndexService")
public interface AutoIndexService
{   
    /**
     * Gets a list of candidate indexes on a table for suggested creation.
     * @param catalog - catalog of table
     * @param schema - schema of table
     * @param table - table to check
     * @param threshold - threshold 0-100 is cut-off percentage
     * @return XML-string of candidate indexes.
     * &lt;indexes&gt;&lt;column column_name="name" /&gt;&lt;/indexes&gt;
     */
    @WebMethod
    @GET
    @Path("/get_candidates/{catalog}/{schema}/{table}/{threshold}")
    @RolesAllowed( {"Admin", "Authenticated"} )
    XMLStructure getCandidates(@PathParam("catalog") String catalog,
        @PathParam("schema") String schema,
        @PathParam("table") String table, @PathParam("threshold") int threshold)
    throws AppException;

    /**
     * Uses the list of indexes generated by a show_idx_candidates() call
     * given the parameters to actually create the indexes.
     * @param catalog - catalog of table
     * @param schema - schema of table
     * @param table - table to check
     * @param threshold - threshold 0-100 is cut-off percentage
     * @return Error message if any, otherwise empty string.
     */
    @WebMethod
    @GET
    @Path("/create_indexes/{catalog}/{schema}/{table}/{threshold}")
    @RolesAllowed( {"Admin", "Authenticated"} )
    String createIndexes(@PathParam("catalog") String catalog,
        @PathParam("schema") String schema,
        @PathParam("table") String table, @PathParam("threshold") int threshold)
    throws AppException;

}
